.changeset/public-flowers-double.md
apps/frontend/src/components/Filters/FiltersContext.tsx

- fix filters context - wrong amount of applied filters

fix: fix filters context

---

.changeset/better-doors-repair.md
apps/frontend/src/components/Pagination/Pagination.tsx
packages/integrations/mocked/src/modules/cms/mappers/cms.article-list.mapper.ts
packages/integrations/mocked/src/modules/cms/mappers/cms.invoice-list.mapper.ts
packages/integrations/mocked/src/modules/cms/mappers/cms.notification-list.mapper.ts
packages/integrations/mocked/src/modules/cms/mappers/cms.resource-list.mapper.ts
packages/integrations/mocked/src/modules/cms/mappers/cms.ticket-list.mapper.ts

fix: bug-43 - fix pagination description

---

.changeset/tidy-papayas-see.md
apps/api-harmonization/src/blocks/user-account/user-account.request.ts
apps/api-harmonization/src/blocks/user-account/user-account.service.ts
apps/frontend/src/blocks/UserAccount/UserAccount.server.tsx
packages/integrations/mocked/src/modules/users/users.mapper.ts

- fix inconsistent data in User Profile

fix: fix inconsistent data in User Profile

---

.changeset/shaggy-papers-pay.md
package-lock.json
packages/framework/package.json
packages/framework/src/interceptors.ts
packages/framework/src/sdk.ts
packages/framework/src/utils/logger.ts

feat: replace axios with ofetch

---

.changeset/green-suns-rhyme.md
apps/api-harmonization/src/modules/page/page.mapper.ts
apps/api-harmonization/src/modules/page/page.model.ts
apps/frontend/src/app/[locale]/[[...slug]]/page.tsx
apps/frontend/src/components/Breadcrumbs/Breadcrumbs.tsx
apps/frontend/src/components/Breadcrumbs/Breadcrumbs.types.ts
packages/framework/src/modules/cms/models/page.model.ts
packages/integrations/mocked/src/modules/cms/mappers/cms.page.mapper.ts
packages/integrations/strapi-cms/generated/strapi.ts
packages/integrations/strapi-cms/src/modules/cms/graphql/fragments/Page.graphql
packages/integrations/strapi-cms/src/modules/cms/mappers/cms.page.mapper.ts

feat: add breadcrumbs

---

.changeset/seven-items-play.md
apps/frontend/src/containers/Footer/Footer.tsx
apps/frontend/src/containers/Header/DesktopNavigation/DesktopNavigation.tsx
packages/ui/src/components/navigation-menu.tsx
packages/ui/src/globals.css
packages/utils/logger/src/modules/logger.module.ts

fix: fix incorrect colors in the Navbar and the Footer

fix: fix incorrect colors in navbar and footer

---

apps/api-harmonization/src/app.module.ts
apps/api-harmonization/turbo/generators/config.ts
apps/api-harmonization/turbo/generators/templates/block/controller.hbs
apps/api-harmonization/turbo/generators/templates/block/model.hbs
apps/api-harmonization/turbo/generators/templates/block/service.hbs
apps/frontend/turbo/generators/templates/block/server.hbs
turbo/generators/config.ts
turbo/generators/templates/integration/module-index.hbs

fix: update generators

---

README.md
apps/docs/docusaurus.config.ts
apps/docs/vercel.json

- updated links to discord to a proper invite URL

docs: udpated links to discord

---

.commitlintrc.yml
.husky/commit-msg
package-lock.json
package.json

Added commitlint to enforce conventional commits.

feat: add commitlint to enforce conventional commits

---

.changeset/bright-turtles-rest.md
apps/frontend/src/blocks/NotificationList/NotificationList.client.tsx
apps/frontend/src/blocks/TicketList/TicketList.client.tsx
apps/frontend/src/components/RichText/RichText.tsx

Making coherent of implementing actions in tables.
Adjusting to figma links in RichText component.

fix: coherence of action buttons in tables

---

.changeset/cold-papayas-join.md
.changeset/fair-colts-shake.md
.changeset/silver-pants-run.md
.changeset/wicked-foxes-clap.md
apps/api-harmonization/src/blocks/orders-summary/orders-summary.mapper.ts
apps/frontend/src/blocks/OrdersSummary/OrdersSummary.client.tsx
packages/framework/src/modules/cms/models/blocks/orders-summary.model.ts
packages/integrations/mocked/src/modules/cms/mappers/blocks/cms.orders-summary.mapper.ts
packages/integrations/strapi-cms/generated/strapi.ts
packages/integrations/strapi-cms/src/modules/cms/cms.service.ts
packages/integrations/strapi-cms/src/modules/cms/graphql/fragments/blocks/OrdersSummary.graphql
packages/integrations/strapi-cms/src/modules/cms/graphql/queries/getComponent.graphql
packages/integrations/strapi-cms/src/modules/cms/graphql/queries/getPage.graphql
packages/integrations/strapi-cms/src/modules/cms/mappers/blocks/cms.orders-summary.mapper.ts
packages/integrations/strapi-cms/src/modules/cms/mappers/cms.page.mapper.ts

- added Strapi integration for `OrdersSummary` block

feat(integrations.strapi-cms): added Strapi integration for `OrdersSummary` block

---

.changeset/quiet-boats-drum.md
.changeset/sharp-rocks-try.md
apps/api-harmonization/src/modules/page/page.service.ts
apps/frontend/src/api/blocks/order-details.ts
apps/frontend/src/app/[locale]/[[...slug]]/page.tsx
apps/frontend/src/app/[locale]/not-found.tsx
apps/frontend/src/app/error.tsx
apps/frontend/src/blocks/OrderDetails/OrderDetails.client.tsx
apps/frontend/src/blocks/OrderDetails/OrderDetails.renderer.tsx
apps/frontend/src/blocks/OrderDetails/OrderDetails.types.ts

Fixed:
- image issue on order-details page,
- error on Error page : 
"Uncaught Error: No intl context found. Have you configured the provider?"

fix(frontend): fixed image issue on OrderDetails page, fixed error page issue, 

---

.changeset/loud-glasses-leave.md
packages/integrations/strapi-cms/generated/strapi.ts
packages/integrations/strapi-cms/src/modules/cms/mappers/cms.survey.mapper.ts

- adjusted strapi survey mapper to match new multiselect type

feat: strapi survey mapper changes after adding multiselect plugin

---

.changeset/quick-loops-share.md
packages/integrations/medusajs/src/modules/orders/orders.mapper.ts
packages/integrations/medusajs/src/modules/orders/orders.service.ts

- fixed mapping of orders from medusajs

fix: fixed mapping of orders from medusajs

---

.changeset/rotten-meals-help.md
apps/api-harmonization/src/modules/page/page.service.ts
packages/integrations/strapi-cms/generated/strapi.ts
packages/integrations/strapi-cms/src/modules/articles/articles.mapper.ts
packages/integrations/strapi-cms/src/modules/articles/articles.service.ts
packages/integrations/strapi-cms/src/modules/articles/graphql/fragments/Article.graphql
packages/integrations/strapi-cms/src/modules/articles/graphql/queries/getArticle.graphql

- remodeled how articles are kept in Strapi in order to suppport indexing them by search engines (e.g. Algolia) by separating them into their own content type

feat: remodeled how articles are kept in Strapi

---

.changeset/fine-llamas-hang.md
packages/framework/src/modules/billing-accounts/billing-accounts.controller.ts
packages/framework/src/modules/invoices/invoices.controller.ts
packages/framework/src/modules/notifications/notifications.controller.ts
packages/framework/src/modules/organizations/organizations.controller.ts
packages/framework/src/modules/products/products.controller.ts
packages/framework/src/modules/resources/resources.controller.ts
packages/framework/src/modules/tickets/tickets.controller.ts
packages/framework/src/modules/users/users.controller.ts

- added passing of authorization header to most of crucial services

feat: added passing of authorization header to most of crucial services

---

.changeset/brown-sloths-stick.md
packages/framework/src/modules/users/users.controller.ts
packages/framework/src/modules/users/users.service.ts
packages/integrations/mocked/src/modules/users/users.service.ts

- added delete user with id method in users module

feat: added user id in delete method params

---

.changeset/upset-candies-peel.md
apps/frontend/src/components/Cards/InfoCard/InfoCard.tsx
packages/framework/src/modules/products/products.request.ts
packages/integrations/medusajs/src/modules/products/products.service.ts
packages/integrations/mocked/src/modules/products/products.mapper.ts
packages/integrations/mocked/src/modules/resources/mock/products.mock.ts
packages/integrations/mocked/src/modules/resources/resources.mapper.ts

feat: update products, resources mocks, InfoCard - layout fix
- updated model for GetRelatedProductListParams - renamed id and variantId to inform that we need to provide product data as params, 
- added natural data to products and resources mocks,
- added sorting and filtering to products.mapper.ts,
- fixed InfoCard layout issue,

feat: update mocks, InfoCard - layout fix

---

.changeset/metal-deer-beam.md
packages/integrations/mocked/src/modules/products/products.mapper.ts
packages/integrations/mocked/src/modules/resources/resources.mapper.ts

- fixed pagination in products and resources mocks

fix: fixed pagination in products and resources mocks

---

.changeset/clever-suns-boil.md
apps/api-harmonization/src/blocks/payments-history/payments-history.mapper.ts
apps/api-harmonization/src/blocks/payments-summary/payments-summary.mapper.ts
apps/api-harmonization/src/blocks/user-account/user-account.module.ts

- replaced chart to be based on issueDate field

feat: replaced chart to be based on issueDate field

---

.changeset/shiny-bears-flow.md
apps/frontend/src/app/[locale]/[[...slug]]/page.tsx
apps/frontend/src/components/Breadcrumbs/Breadcrumbs.tsx
apps/frontend/src/utils/breadcrumb.ts
packages/integrations/mocked/src/modules/articles/mocks/categories.mocks.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/category.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/invoice-list.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/notification-details.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/notification-list.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/order-details.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/order-list.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/service-details.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/service-list.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/surveyjs-forms.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/ticket-details.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/ticket-list.page.ts
packages/integrations/mocked/src/modules/cms/mappers/mocks/pages/user-account.page.ts

- fixed breadcrumb - removed redundant dashboard text

fix: fixed breadcrumb - removed redundant dashboard text

---

.changeset/pink-candies-rule.md
apps/api-harmonization/turbo/generators/templates/block/module.hbs
apps/api-harmonization/turbo/generators/templates/block/service.hbs

fixed api-harmonization generator

fix: fixed api-harmonization generator

---

.changeset/afraid-cows-appear.md
.changeset/famous-needles-smoke.md
.changeset/tasty-buckets-add.md
apps/api-harmonization/src/modules/page/page.service.ts
packages/framework/src/modules/organizations/organizations.controller.ts
packages/framework/src/modules/organizations/organizations.model.ts
packages/framework/src/modules/organizations/organizations.request.ts
packages/framework/src/modules/organizations/organizations.service.ts
packages/framework/src/modules/users/users.model.ts
packages/framework/src/modules/users/users.request.ts
packages/framework/src/modules/users/users.service.ts
packages/integrations/mocked/src/modules/organizations/organizations.mapper.ts
packages/integrations/mocked/src/modules/organizations/organizations.service.ts
packages/integrations/mocked/src/modules/users/users.mapper.ts
packages/integrations/mocked/src/modules/users/users.service.ts

Extending the User and Organization model for checking user membership

feat: extending the User and Organization model for checking user membership
